<?php
class Ant_Api_Model_Mysql4_Webhook_Cron_Schedule_Collection extends Mage_Core_Model_Mysql4_Collection_Abstract {
    function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_init("ant_api/webhook_cron_schedule");
    }
    protected function addWebhookUrl() {
        $cond = 'main_table.webhook_id = ant_webhook.ant_api_webhook_id';
        $this->join(array('ant_webhook' => 'webhook'), $cond, array());
    }
}