<?php
class Ant_Api_Model_Webhook extends Mage_Core_Model_Abstract{

    public function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_init("ant_api/webhook");
    }
}