<?php
class Ant_Api_Model_Webhook extends Mage_Core_Model_Abstract{

    const PRODUCT_CREATE = "product.create";
    const PRODUCT_DELETE = "product.delete";
    const PRODUCT_UPDATE = "product.update";
    const CUSTOMER_CREATE = "customer.create";
    const CUSTOMER_DELETE = "customer.delete";
    const CUSTOMER_UPDATE = "customer.update";
    const ORDER_CREATE = "order.create";
    const ORDER_DELETE = "order.delete";
    const ORDER_UPDATE = "order.update";

    public function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_init("ant_api/webhook");
    }
}