<?php

class Ant_Api_Model_Webhook_Cron_Schedule extends Mage_Core_Model_Abstract {

    const CACHE_TAG              = 'ant_api_webhook';
    protected $_cacheTag         = 'ant_api_webhook';

    const STATUS_QUEUED   = 0;
    const STATUS_PROGRESS = 1;
    const STATUS_SUCCESS  = 2;
    const STATUS_FAILED   = 3;

    /**
     * Initialize resource model
     *
     */
    protected function _construct() {
        $this->_init('ant_api/webhook_cron_schedule');
    }

    protected function _beforeSave() {
        if (!$this->getStatus()) {
            $this->setStatus(self::STATUS_QUEUED);
        }
        
        
        return parent::_beforeSave(); // TODO: Change the autogenerated stub
    }

}