<?php
class Ant_Api_Model_Webhook_Cron_Schedule extends Mage_Core_Model_Abstract {
    const CACHE_TAG              = 'ant_api_webhook';
    protected $_cacheTag         = 'ant_api_webhook';
    const STATUS_QUEUED   = 0;
    const STATUS_PROGRESS = 1;
    const STATUS_SUCCESS  = 2;
    const STATUS_FAILED   = 3;
    /**
     * Initialize resource model
     *
     */
    protected function _construct() {
        $this->_init('ant_api/webhook_cron_schedule');
    }
    protected function _beforeSave() {
        if (!$this->getStatus()) {
            $this->setStatus(self::STATUS_QUEUED);
        }


        return parent::_beforeSave(); // TODO: Change the autogenerated stub
    }

    /**
     * Get most recent checksum from the resource
     *
     * @return $this
     */
    public function getMostRecentChecksum() {
        $this->_getResource()->getMostRecentChecksum($this);
        return $this;
    }
    /**
     * Check if the most recent checksum is the same as the given checksum
     *
     * @param $checksum
     *
     * @return bool
     */
    public function needsChecksumUpdated($checksum) {
        $recentChecksum = $this->getMostRecentChecksum();
        if ($recentChecksum == $checksum) {
            return false;
        }
            return true;
        }

}