<?php
class Ant_Api_Model_Mysql4_Webhook_Cron_Schedule extends Mage_Core_Model_Mysql4_Abstract {


    protected $_serializableFields = array(
    'request_data'    => array(array(), null),
    );


    public function _construct()
    {
        // TODO: Implement _construct() method.
        $this->_init("ant_api/webhook_cron_schedule","process_id");
    }

    public function _beforeSave(Mage_Core_Model_Abstract $object) {
        // modify create / update dates

        if ($object->isObjectNew() && !$object->hasCreatedAt()) {
            $object->setCreatedAt(Mage::getSingleton('core/date')->gmtDate());
        }

        $object->setUpdatedAt(Mage::getSingleton('core/date')->gmtDate());

        return parent::_beforeSave($object); // TODO: Change the autogenerated stub
    }
}